---
resources:
  - name: pcf-demo-ci
    type: git
    source:
      uri: https://github.com/patrickcrocker/PCF-demo-ci.git
      branch: master
  - name: pcf-demo
    type: git
    source:
      uri: https://github.com/patrickcrocker/PCF-demo.git
      branch: master

jobs:
  - name: unit-test
    public: true
    plan:
      - get: pcf-demo-ci
      - get: pcf-demo
        trigger: true
      - task: unit
        file: pcf-demo-ci/concourse/tasks/unit.yml
  - name: build-artifact
    public: true
    plan:
      - get: pcf-demo-ci
        passed: [ unit-test ]
        trigger: true
      - get: pcf-demo
        passed: [ unit-test ]
        trigger: true
      - task: build
        file: pcf-demo-ci/concourse/tasks/build.yml
        privileged: true
